import 'package:flutter/material.dart';
import 'package:islami_project_again/islami_project_practice/module/layouts/sura_details.dart';
import 'package:flutter_gen/gen_l10n/app_localizations.dart';

class QuranScreen extends StatelessWidget {
   QuranScreen({super.key});
var chapters=[
  "Al-Fatiha",
  "Al-Baqarah",
  "Aal-E-Imran",
  "An-Nisa'",
  "Al-Ma'idah",
  "Al-An'am",
  "Al-A'raf",
  "Al-Anfal",
  "At-Tawbah",
  "Yunus",
  "Hud",
  "Yusuf",
  "Ar-Ra'd",
  "Ibrahim",
  "Al-Hijr",
  "An-Nahl",
  "Al-Isra",
  "Al-Kahf",
  "Maryam",
  "Ta-Ha",
  "Al-Anbiya",
  "Al-Hajj",
  "Al-Mu'minun",
  "An-Nur",
  "Al-Furqan",
  "Ash-Shu'ara",
  "An-Naml",
  "Al-Qasas",
  "Al-Ankabut",
  "Ar-Rum",
  "Luqman",
  "As-Sajda",
  "Al-Ahzab",
  "Saba",
  "Fatir",
  "Ya-Sin",
  "As-Saffat",
  "Sad",
  "Az-Zumar",
  "Ghafir",
  "Fussilat",
  "Ash-Shura",
  "Az-Zukhruf",
  "Ad-Dukhan",
  "Al-Jathiya",
  "Al-Ahqaf",
  "Muhammad",
  "Al-Fath",
  "Al-Hujurat",
  "Qaf",
  "Adh-Dhariyat",
  "At-Tur",
  "An-Najm",
  "Al-Qamar",
  "Ar-Rahman",
  "Al-Waqi'a",
  "Al-Hadid",
  "Al-Mujadila",
  "Al-Hashr",
  "Al-Mumtahina",
  "As-Saff",
  "Al-Jumu'a",
  "Al-Munafiqun",
  "At-Taghabun",
  "At-Talaq",
  "At-Tahrim",
  "Al-Mulk",
  "Al-Qalam",
  "Al-Haqqah",
  "Al-Ma'arij",
  "Nuh",
  "Al-Jinn",
  "Al-Muzzammil",
  "Al-Muddathir",
  "Al-Qiyamah",
  "Al-Insan",
  "Al-Mursalat",
  "An-Naba'",
  "An-Nazi'at",
  "Abasa",
  "At-Takwir",
  "Al-Infitar",
  "Al-Mutaffifin",
  "Al-Inshiqaq",
  "Al-Buruj",
  "At-Tariq",
  "Al-A'la",
  "Al-Ghashiyah",
  "Al-Fajr",
  "Al-Balad",
  "Ash-Shams",
  "Al-Lail",
  "Ad-Duha",
  "Ash-Sharh",
  "At-Tin",
  "Al-Alaq",
  "Al-Qadr",
  "Al-Bayyina",
  "Az-Zalzalah",
  "Al-Adiyat",
  "Al-Qari'a",
  "At-Takathur",
  "Al-Asr",
  "Al-Humazah",
  "Al-Fil",
  "Quraysh",
  "Al-Ma'un",
  "Al-Kawthar",
  "Al-Kafirun",
  "An-Nasr",
  "Al-Masad",
  "Al-Ikhlas",
  "Al-Falaq",
  "An-Nas"
];
 var arabicChapters = [
     "الفاتحه",
     "البقرة",
     "آل عمران",
     "النساء",
     "المائدة",
     "الأنعام",
     "الأعراف",
     "الأنفال",
     "التوبة",
     "يونس",
     "هود",
     "يوسف",
     "الرعد",
     "إبراهيم",
     "الحجر",
     "النحل",
     "الإسراء",
     "الكهف",
     "مريم",
     "طه",
     "الأنبياء",
     "الحج",
     "المؤمنون",
     "النّور",
     "الفرقان",
     "الشعراء",
     "النّمل",
     "القصص",
     "العنكبوت",
     "الرّوم",
     "لقمان",
     "السجدة",
     "الأحزاب",
     "سبأ",
     "فاطر",
     "يس",
     "الصافات",
     "ص",
     "الزمر",
     "غافر",
     "فصّلت",
     "الشورى",
     "الزخرف",
     "الدّخان",
     "الجاثية",
     "الأحقاف",
     "محمد",
     "الفتح",
     "الحجرات",
     "ق",
     "الذاريات",
     "الطور",
     "النجم",
     "القمر",
     "الرحمن",
     "الواقعة",
     "الحديد",
     "المجادلة",
     "الحشر",
     "الممتحنة",
     "الصف",
     "الجمعة",
     "المنافقون",
     "التغابن",
     "الطلاق",
     "التحريم",
     "الملك",
     "القلم",
     "الحاقة",
     "المعارج",
     "نوح",
     "الجن",
     "المزّمّل",
     "المدّثر",
     "القيامة",
     "الإنسان",
     "المرسلات",
     "النبأ",
     "النازعات",
     "عبس",
     "التكوير",
     "الإنفطار",
     "المطفّفين",
     "الإنشقاق",
     "البروج",
     "الطارق",
     "الأعلى",
     "الغاشية",
     "الفجر",
     "البلد",
     "الشمس",
     "الليل",
     "الضحى",
     "الشرح",
     "التين",
     "العلق",
     "القدر",
     "البينة",
     "الزلزلة",
     "العاديات",
     "القارعة",
     "التكاثر",
     "العصر",
     "الهمزة",
     "الفيل",
     "قريش",
     "الماعون",
     "الكوثر",
     "الكافرون",
     "النصر",
     "المسد",
     "الإخلاص",
     "الفلق",
     "الناس"
   ];
var arabicnumbers= [
  '١', '٧', '٢٨٦', '٢٠٠', '١٧٦', '١٢٠', '١٦٥', '٢٠٦', '٧٥', '١٢٩', '١٠٩', '١٢٣', '١١١',
  '٤٣', '٥٢', '٩٩', '١٢٨', '١١١', '١١٠', '٩٨', '١٣٥', '١١٢', '٧٨', '١١٨', '٦٤', '٧٧',
  '٢٢٧', '٩٣', '٨٨', '٦٩', '٦٠', '٣٤', '٣٠', '٧٣', '٥٤', '٤٥', '٨٣', '١٨٢', '٨٨', '٧٥',
  '٨٥', '٥٤', '٥٣', '٨٩', '٥٩', '٣٧', '٣٥', '٣٨', '٢٩', '١٨', '٤٥', '٦٠', '٤٩', '٦٢',
  '٥٥', '٧٨', '٩٦', '٢٩', '٢٢', '٢٤', '١٣', '١٤', '١١', '١١', '١٨', '١٢', '١٢', '٣٠',
  '٥٢', '٥٢', '٤٤', '٢٨', '٢٨', '٢٠', '٥٦', '٤٠', '٣١', '٥٠', '٤٠', '٤٦', '٤٢', '٢٩',
  '١٩', '٣٦', '٢٥', '٢٢', '١٧', '١٩', '٢٦', '٣٠', '٢٠', '١٥', '٢١', '١١', '٨', '٥', '١٩',
  '٥', '٨', '٨', '١١', '١١', '٨', '٣', '٩', '٥', '٤', '٦', '٣', '٦', '٣', '٥', '٤', '٥', '٦'
];
var numbersofAyat= [
     '7',
     '286',
     '200',
     '176',
     '120',
     '165',
     '206',
     '75',
     '129',
     '109',
     '123',
     '111',
     '43',
     '52',
     '99',
     '128',
     '111',
     '110',
     '98',
     '135',
     '112',
     '78',
     '118',
     '64',
     '77',
     '227',
     '93',
     '88',
     '69',
     '60',
     '34',
     '30',
     '73',
     '54',
     '45',
     '83',
     '182',
     '88',
     '75',
     '85',
     '54',
     '53',
     '89',
     '59',
     '37',
     '35',
     '38',
     '29',
     '18',
     '45',
     '60',
     '49',
     '62',
     '55',
     '78',
     '96',
     '29',
     '22',
     '24',
     '13',
     '14',
     '11',
     '11',
     '18',
     '12',
     '12',
     '30',
     '52',
     '52',
     '44',
     '28',
     '28',
     '20',
     '56',
     '40',
     '31',
     '50',
     '40',
     '46',
     '42',
     '29',
     '19',
     '36',
     '25',
     '22',
     '17',
     '19',
     '26',
     '30',
     '20',
     '15',
     '21',
     '11',
     '8',
     '5',
     '19',
     '5',
     '8',
     '8',
     '11',
     '11',
     '8',
     '3',
     '9',
     '5',
     '4',
     '6',
     '3',
     '6',
     '3',
     '5',
     '4',
     '5',
     '6'
   ];
  @override
  Widget build(BuildContext context) {
    bool isArabic = Localizations.localeOf(context).languageCode == 'ar';
    var usedChapters=isArabic ? arabicChapters : chapters;
    var usedNums=isArabic ? arabicnumbers : numbersofAyat;

    return Scaffold(
      // when add appBar: AppBar(
      //         backgroundColor: Colors.blue,
      //       ),  it makes another app bar
      body: Column(

        crossAxisAlignment:CrossAxisAlignment.center ,
        mainAxisAlignment: MainAxisAlignment.start,
        children: [
          Image.asset("assets/images/qur2an_screen_logo.png"),
          Divider(
            thickness: 2,
            color: Color(0xffB7935F),
          ),
          IntrinsicHeight(
            child: Row(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                Expanded(
                  child: Text(AppLocalizations.of(context)!.chapterTitle,
                      style: Theme.of(context).textTheme.titleMedium),
                ),
                VerticalDivider(
                  color: Color(0xffB7935F),
                  thickness: 2,
                ),
                Expanded(
                  child: Text(AppLocalizations.of(context)!.numberOfTheAyat,
                      style:  Theme.of(context).textTheme.bodyMedium),
                ),
              ],
            ),
          ),

          Divider(
            thickness: 2,
            color: Color(0xffB7935F),
          ),
          Expanded(
              child: ListView.builder(itemBuilder: (context,index){
                return IntrinsicHeight(
                  child: Row(
                    mainAxisAlignment: MainAxisAlignment.center,
                    children: [
                      Expanded(
                        child: InkWell(
                          onTap:(){
                            Navigator.pushNamed(context, SuraDetails.routname,
                                arguments: SuraDetailsArgu(index, usedChapters[index]));
                          },
                          child: FittedBox(
                            child: Text(usedChapters[index],
                              style: Theme.of(context).textTheme.bodyMedium),
                          ),
                        ),
                      ),
                      Expanded(
                        child: VerticalDivider(
                          color: Colors.black,
                          thickness: 2,
                        ),
                      ),
                      Expanded(child: Text(usedNums[index] , style: Theme.of(context).textTheme.bodyMedium)),
                    ],
                  ),
                );
              },
              itemCount:chapters.length ,
              ))
        ],
      ),
    );
  }
}
